### ISSUE TITLE
Wrong number of arguments after upgrading to Rails 4.1.10

### ISSUE THREAD

**Issue by baburdick** [albertosaurus/power_enum#25]
```
       ArgumentError:
         wrong number of arguments (1 for 0)
       # power_enum-2.8.0/lib/power_enum/reflection.rb:115:in `association_primary_key'
       # activerecord-4.1.10/lib/active_record/relation/predicate_builder.rb:64:in `expand'
       # activerecord-4.1.10/lib/active_record/relation/predicate_builder.rb:43:in `block in build_from_hash'
       # activerecord-4.1.10/lib/active_record/relation/predicate_builder.rb:21:in `each'
       # activerecord-4.1.10/lib/active_record/relation/predicate_builder.rb:21:in `build_from_hash'
       # activerecord-4.1.10/lib/active_record/relation/query_methods.rb:954:in `build_where'
       # activerecord-4.1.10/lib/active_record/relation/query_methods.rb:572:in `where!'
       # activerecord-4.1.10/lib/active_record/relation/query_methods.rb:559:in `where'
       # activerecord-4.1.10/lib/active_record/querying.rb:10:in `where'
```

**Comment by albertosaurus** [comment]
Will try to look at this tonight, if not, weekend.

**Comment by baburdick** [comment]
Wrong repo. Sorry. Issue created in the proper place: https://github.com/albertosaurus/power_enum_2/issues/10
